version: "3.7"

services:
    # docker run --name %containerName% --memory 2GB --mount "type=bind,source=%hostDirectory%,destination=C:\CosmosDB.Emulator\bind-mount"  --interactive --tty -p 8081:8081 -p 8900:8900 -p 8901:8901 -p 8979:8979 -p 10250:10250 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -p 10255:10255 -p 10256:10256 -p 10350:10350 microsoft/azure-cosmosdb-emulator
    cosmosdb:
        # image: mcr.microsoft.com/cosmosdb/windows/azure-cosmos-emulator
        image: microsoft/azure-cosmosdb-emulator
        ports: 
            - "8081:8081"
            - "8900:8900"
            - "8901:8901"
            - "8979:8979"
            - "10250:10250"
            - "10251:10251"
            - "10252:10252"
            - "10253:10253"
            - "10254:10254"
            - "10255:10255"
            - "10256:10256"
            - "10350:10350"
        volumes: 
            - type: bind
              source: .\azure-cosmosdb-emulator.hostd
              target: C:\CosmosDB.Emulator\bind-mount
        tty: true
        stdin_open: true
